### ISSUE TITLE
[Bug] Error generating the file transcription. Please try again.

### ISSUE THREAD

**Issue by dandud100** [HenestrosaDev/audiotext#10]
Steps to reproduce
------------------

1. Use the audio from the following video: https://www.youtube.com/watch?v=Mlpu32AIt8I
2. Try to transcribe it (german)
3. "Error generating the file transcription. Please try again." is shown after like 5 seconds in the program

System information
------------------

(Delete all statements that don't apply.)

- **System**: "Windows 11 x64"
- **System language**: deDE
- **Audiotext version**: 1.2.4

**Comment by HenestrosaDev** [comment]
Thanks for the details. I'll try to fix it this weekend.

**Comment by HenestrosaDev** [comment]
Hi.

I've fixed the issue in the [new release](https://github.com/HenestrosaDev/audiotext/releases/tag/v2.0.0). I've also made some improvements to the program, like adding WhisperX support for fast and unlimited transcriptions. If you encounter any issue, please create a new one.
