### ISSUE TITLE
CUDA error when CPU selected

### ISSUE THREAD

**Issue by wimj888** [HenestrosaDev/audiotext#12]
Steps to reproduce
------------------

I got a CUDA error on several retries to transcribe an English mp3 file of about 4 MB on Windows 11.
Version of audiotext used was 2.1.0

Expected behaviour
------------------

Transcribed text of audio file

Actual behaviour
----------------

Traceback (most recent call last):
  File "controller\main_controller.py", line 170, in _transcribe_using_whisperx
  File "whisperx\asr.py", line 287, in load_model
    model = model or WhisperModel(whisper_arch,
  File "faster_whisper\transcribe.py", line 130, in __init__
RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

![image](https://github.com/HenestrosaDev/audiotext/assets/69757595/b07efee4-7a7b-4278-afdd-8e080a1f2ffa)

**Comment by wimj888** [comment]
As this might be related to the ffmpeg install, following is the output on my system :

![image](https://github.com/HenestrosaDev/audiotext/assets/69757595/83edb2f1-18ec-4a70-a64e-fcb8e0f08afa)

**Comment by HenestrosaDev** [comment]
Thanks for the detailed information. I'll take a look at this tomorrow as it seems to be related to the logic that handles changing the value of the "Use CPU" checkbox.

**Comment by HenestrosaDev** [comment]
> As this might be related to the ffmpeg install, following is the output on my system :
> 
> ![image](https://private-user-images.githubusercontent.com/69757595/293698715-83edb2f1-18ec-4a70-a64e-fcb8e0f08afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDc1ODQsIm5iZiI6MTcwNDcwNzI4NCwicGF0aCI6Ii82OTc1NzU5NS8yOTM2OTg3MTUtODNlZGIyZjEtMThlYy00YTcwLWE2NGUtZmNiOGUwZjA4YWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5NDgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZThhOTRiMWI2NDk0NGMxYmJlYjhlZTVmZjJkYWRhNDkyYzJjNzMxMzdjMzhhZWZhNmFmMWZkN2NjYWY5NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M7II_fDt6BPaUw-SgIXZyPy9WWR5laU-05aOuM-JZnw)
> 
> I got around it by editing the config.ini and settting use_cpu = **True** For some reason this is not done via the GUI.

I've checked this and it seems to be working fine. The config value is updated correctly according to the checkbox value.
