### ISSUE TITLE
Transcription of media with filipino source language not available due to value error

### ISSUE THREAD

**Issue by gerardhades003** [HenestrosaDev/audiotext#16]
I was trying to transcribe a video with Filipino source language, and translate it to English, but this error pops up:

![image](https://github.com/HenestrosaDev/audiotext/assets/169884221/79e2a202-a69d-4bd5-bde2-ba8e46cc035a)

**Comment by HenestrosaDev** [comment]
Hi! Sorry for the inconvenience. Just to be sure, is Filipino the same as Tagalog?

**Comment by gerardhades003** [comment]
Hello! Technically yes, Filipino is somewhat similar to Tagalog. (90% Tagalog)

**Comment by HenestrosaDev** [comment]
Alright. It seems that WhisperX only supports Tagalog, so I'll update the project to include Tagalog instead of Filipino. I'll close the issue as soon as I release the update.

**Comment by gerardhades003** [comment]
Alright, thank you!!!! Have a nice day today.

**Comment by HenestrosaDev** [comment]
Fixed in version 2.2.1.
