### ISSUE TITLE
RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by olawalejuwonm** [HenestrosaDev/audiotext#40]
Steps to reproduce
------------------

I followed the guide here https://github.com/HenestrosaDev/audiotext#set-up-the-project-locally

With these options:
![image](https://github.com/user-attachments/assets/baba0be5-a1e5-4316-aaa6-cd14da3a5f9e)

Expected behaviour
------------------
It should transcribe the audio file selected

Actual behaviour
----------------

Errors out: RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

```
(If the library threw an exception, paste the full stack trace here)
```
Traceback (most recent call last):
  File "C:\Users\HP\Documents\GitHub\Tarm\audiotext\src\handlers\whisperx_handler.py", line 30, in transcribe_file
    model = whisperx.load_model(
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Documents\GitHub\Tarm\audiotext\.venv\Lib\site-packages\whisperx\asr.py", line 288, in load_model
    model = model or WhisperModel(whisper_arch,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Documents\GitHub\Tarm\audiotext\.venv\Lib\site-packages\faster_whisper\transcribe.py", line 133, in __init__
    self.model = ctranslate2.models.Whisper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

System information
------------------

(Delete all statements that don't apply.)

- **System**: "Windows 10 x64"
- **System language**: (Please, indicate the region as well): English
- **Audiotext version**: v2.2.3

**Comment by HenestrosaDev** [comment]
Can you share your CPU and GPU models? I don't understand why you get the CUDA error having the `Use CPU` option checked. It would only make sense if you were using the GPU to generate the transcription.

**Comment by HenestrosaDev** [comment]
Follow these steps on Windows 10 to check your CPU model:
1. Press <kbd><kbd>Windows</kbd> + <kbd>I</kbd></kbd> and select "System".
2. Scroll down the sidebar to the bottom and click "About".
3. Copy and paste here the "Processor".

To find your GPU model on Windows 10, do the following:
1. In the search box on the taskbar, type "System information" and open it.
2. In the system Information window, expand the "Components" option.
3. Click on "Display".
4. Copy and paste the value of "Name".

**Comment by HenestrosaDev** [comment]
1. Can you change the compute type setting to `int8`?
2. If the problem still persists after doing 1), please share the contents of your `config.ini` file. It's located in the root of the `audiotext-v2.2.3` folder.

**Comment by olawalejuwonm** [comment]
> 1. Can you change the compute type setting to `int8`?
> 2. If the problem still persists after doing 1), please share the contents of your `config.ini` file. It's located in the root of the `audiotext-v2.2.3` folder.

Option 1 doesn't work.
2. [whisperx]
model_size = tiny
batch_size = 8
compute_type = float16
use_cpu = False
can_use_gpu = False
output_file_types = txt

[google_api]
api_key = 

[subtitles]
highlight_words = False
max_line_width = 42
max_line_count = 2

[system]
appearance_mode = System

**Comment by HenestrosaDev** [comment]
Change `use_cpu = False` to `use_cpu = True`. This should fix the problem. I have to check why the value doesn't change to `True` on start.

**Comment by olawalejuwonm** [comment]
Yes, it works!

**Comment by olawalejuwonm** [comment]
But I have another issue, I will open in another issue
