### ISSUE TITLE
AttributeError('Could not find PyAudio; check installation')

### ISSUE THREAD

**Issue by olawalejuwonm** [HenestrosaDev/audiotext#44]
Following #40 issue resolution, I tried using transcription from microphone. I got AttributeError('Could not find PyAudio; check installation')

When i do  pip install pyaudio==0.2.13

Here's the output

> Collecting pyaudio==0.2.13
>   Using cached PyAudio-0.2.13.tar.gz (46 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [33 lines of output]
>       Traceback (most recent call last):
>         File "c:\Users\HP\Documents\GitHub\Tarm\audiotext\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>           main()
>         File "c:\Users\HP\Documents\GitHub\Tarm\audiotext\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "c:\Users\HP\Documents\GitHub\Tarm\audiotext\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
>           backend = _build_backend()
>                     ^^^^^^^^^^^^^^^^
>         File "c:\Users\HP\Documents\GitHub\Tarm\audiotext\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
>           obj = import_module(mod_path)
>                 ^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>         File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>         File "C:\Users\HP\AppData\Local\Temp\pip-build-env-ohlyygnb\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
>           import setuptools.version
>         File "C:\Users\HP\AppData\Local\Temp\pip-build-env-ohlyygnb\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>          import pkg_resources
>         File "C:\Users\HP\AppData\Local\Temp\pip-build-env-ohlyygnb\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
>           register_finder(pkgutil.ImpImporter, find_on_path)
>                           ^^^^^^^^^^^^^^^^^^^
>       AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by HenestrosaDev** [comment]
Does this error occur with the `Audiotext.exe` file? If not, please make sure you follow the steps to [set up the project locally](https://github.com/HenestrosaDev/audiotext?tab=readme-ov-file#set-up-the-project-locally).

**Comment by olawalejuwonm** [comment]
It occurs locally and i followed the instructions

**Comment by HenestrosaDev** [comment]
I'll have to take a deeper look into that. In the meantime, I suggest using the program by downloading the [latest version](https://github.com/HenestrosaDev/audiotext/releases/tag/v2.2.3), unzipping it, and running `Audiotext.exe`.

**Comment by olawalejuwonm** [comment]
Ok thanks.

I actually want to make further contributions,  so I need it locally

**Comment by HenestrosaDev** [comment]
This has been resolved in #46. It will be available in version 2.3.0.

**Comment by olawalejuwonm** [comment]
Great!

I should pull?

**Comment by HenestrosaDev** [comment]
Yes, you can.
