### ISSUE TITLE
Run on GPU

### ISSUE THREAD

**Issue by olawalejuwonm** [HenestrosaDev/audiotext#68]
Thanks for the awesome project.

I'm running on windows machine with GPU Model: Intel(R) HD Graphics 520 how do I make the audio-text use this GPU instead of CPU?

**Comment by HenestrosaDev** [comment]
You can't run WhisperX on that GPU because Whisper only supports CUDA GPUs. You can see the official list of CUDA GPUs from [the official website of Nvidia](https://developer.nvidia.com/cuda-gpus).

**Comment by olawalejuwonm** [comment]
Can I get the NIVIDIA GPU for a MacOs?

**Comment by HenestrosaDev** [comment]
No, you can't. Apple has never made Macs with CUDA GPUs.

**Comment by olawalejuwonm** [comment]
oh. I learnt that I can buy the GPU for my windows PC

**Comment by olawalejuwonm** [comment]
I have browsed through and found out:  NVIDIA H100 Tensor Core GPU will
that work?
2. How can I buy it for my Windows PC?
3. How can I buy a device that comes with it?
