### ISSUE TITLE
TypeError("'NoneType' object does not support item assignment")

### ISSUE THREAD

**Issue by Mremenar** [HenestrosaDev/audiotext#69]
Steps to reproduce
------------------

1. (How do you make the issue happen? Does it happen every time you try it?)  YES.
2. (Make sure to go into as much detail as needed to reproduce the issue.) RAN Audiotext.exe FROM DOWNLOAD FOLDER, PROGRAM STARTS.  SELECT MP3 TO TRANSLATE TO TEXT, RUN.  IT RUNS A FEW MINUTES THEN POPS UP ERROR IN TITLE.
3. (If there are any files, like any `strings.xml`, don't forget to include them.)

Expected behaviour
TRANSCRIBE MP3 TO TEXT FILE
------------------

(What did you expect to happen?)

Actual behaviour
NOTHING HAPPENS EXCEPT ERROR MESSAGE
----------------

(What happened instead? How is it different from what you expected?)

FOLLOWING ERROR OCCURRED AFTER CHANGING METHOD TO GOOGLE API:
![AUDIOTEXT ERROR 2](https://github.com/user-attachments/assets/212caf13-2bf2-4fcc-a1ef-626cfeacc74f)
![AUDIOTEXT ERROR](https://github.com/user-attachments/assets/9c881744-adc4-4c3d-b7d0-ca0352971d8e)
Traceback (most recent call last):
  File "handlers\audio_handler.py", line 38, in get_transcription
  File "handlers\audio_handler.py", line 73, in load_audio_file
  File "pydub\audio_segment.py", line 728, in from_file
  File "pydub\utils.py", line 274, in mediainfo_json
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

```
(If the library threw an exception, paste the full stack trace here)
```

System information
------------------

(Delete all statements that don't apply.)

"Windows 10 x64"

Code To Duplicate
------------------

Delete this section if you didn't modify the code.

Screenshot, Sketch, or Drawing
---------------------

Optional. Feel free to provide an image if you think it adds more useful information to the issue.

You can use [this tool](https://www.cockos.com/licecap/) to record GIFs on macOS and Windows, and [this tool](https://github.com/colinkeenan/silentcast) or [this tool](https://github.com/GNOME/byzanz) on Linux.

**Comment by HenestrosaDev** [comment]
The WhisperX bug is already fixed and will be available in the next release. As for the Google API error, have you tried transcribing with Google API before or after selecting WhisperX?

**Comment by Mremenar** [comment]
both.“Fall seven times; stand up eight.”—Japanese proverbOn Sep 24, 2024, at 1:06 AM, HenestrosaDev ***@***.***> wrote:﻿
The WhisperX bug is already fixed and will be available in the next release. As for the Google API error, have you tried transcribing with Google API before or after selecting WhisperX?

**Comment by Mremenar** [comment]
When will the next release be available?

**Comment by Mremenar** [comment]
You can close this bug.  I had an older version of ffmpeg on my machine.  when I updated, it fixed the problem.Thank you,Marc“Fall seven times; stand up eight.”—Japanese proverbOn Sep 24, 2024, at 7:40 AM, Marc Remenar ***@***.***> wrote:﻿both.“Fall seven times; stand up eight.”—Japanese proverbOn Sep 24, 2024, at 1:06 AM, HenestrosaDev ***@***.***> wrote:﻿
The WhisperX bug is already fixed and will be available in the next release. As for the Google API error, have you tried transcribing with Google API before or after selecting WhisperX?

**Comment by Mremenar** [comment]
Thank you for all the time, effort, and energy that you have put into this software.“Fall seven times; stand up eight.”—Japanese proverbOn Sep 25, 2024, at 3:45 PM, HenestrosaDev ***@***.***> wrote:﻿
Closed #69 as completed.

**Comment by HenestrosaDev** [comment]
Thank you for your words! The next version will be available in about 2 weeks.

**Comment by Mremenar** [comment]
Good to know.Your software works with an impressive accuracy.  I’ve been using it to transcribe public speaking events and it is no exaggeration to say it captures and transcribes with a 99% or greater accuracy rate.“Fall seven times; stand up eight.”—Japanese proverbOn Sep 26, 2024, at 12:53 AM, HenestrosaDev ***@***.***> wrote:﻿
Thank you for your words! The next version will be available in about 2 weeks.

**Comment by laminarturbulent** [comment]
@HenestrosaDev I got the same NoneType issue with WhisperX - will you be releasing the version with the fix implemented soon?

**Comment by HenestrosaDev** [comment]
@laminarturbulent I was going to release it a couple of months ago, but I've been super busy since then. This is actually fixed, so I'll try to release a new version with the correction.

**Comment by laminarturbulent** [comment]
Thanks! For anyone else with the same issue, faster-whisper-GUI worked for me: https://github.com/CheshireCC/faster-whisper-GUI
