### ISSUE TITLE
[Bug] ValueError('Error: No valid file selected.')

### ISSUE THREAD

**Issue by olawalejuwonm** [HenestrosaDev/audiotext#70]
The system throws ValueError('Error: No valid file selected.') even after making file selection as shown below:

![image](https://github.com/user-attachments/assets/3abd6a8c-89e4-48e3-b210-c031702ab464)

Through debugging it was noticed it was as a result of file extension being in capital case

**Comment by olawalejuwonm** [comment]
But I got file not found when the file actually exists on windows

**Comment by HenestrosaDev** [comment]
Oh, okay. Now I see what you mean, I thought it was related to a different topic. I've merged your pull request into the `main` branch. Thank you for contributing!

**Comment by olawalejuwonm** [comment]
Awesome, thank you so much!

I was suggesting you add hacktoberfest to the repo so the project attract
more contributions
